// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i4;

import 'package:decimal/decimal.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/controllers/supply_item_manager.dart' as _i18;
import 'package:mona/data/model/administration_route.dart' as _i10;
import 'package:mona/data/model/date.dart' as _i15;
import 'package:mona/data/model/ester.dart' as _i11;
import 'package:mona/data/model/generic_supply_item.dart' as _i7;
import 'package:mona/data/model/graph_calculator.dart' as _i14;
import 'package:mona/data/model/medication_intake.dart' as _i13;
import 'package:mona/data/model/medication_schedule.dart' as _i17;
import 'package:mona/data/model/medication_supply_item.dart' as _i6;
import 'package:mona/data/model/molecule.dart' as _i9;
import 'package:mona/data/model/supply_item.dart' as _i3;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i12;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i16;
import 'package:mona/data/providers/supply_item_provider.dart' as _i5;
import 'package:mona/i18n/locale_provider.dart' as _i20;
import 'package:mona/services/repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupplyItem_1 extends _i1.SmartFake implements _i3.SupplyItem {
  _FakeSupplyItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupplyItemProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemProvider extends _i1.Mock
    implements _i5.SupplyItemProvider {
  MockSupplyItemProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i3.SupplyItem> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i3.SupplyItem>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i3.SupplyItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.SupplyItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  List<_i6.MedicationSupplyItem> get medicationItems => (super.noSuchMethod(
        Invocation.getter(#medicationItems),
        returnValue: <_i6.MedicationSupplyItem>[],
      ) as List<_i6.MedicationSupplyItem>);

  @override
  List<_i7.GenericSupply> get genericItems => (super.noSuchMethod(
        Invocation.getter(#genericItems),
        returnValue: <_i7.GenericSupply>[],
      ) as List<_i7.GenericSupply>);

  @override
  List<_i6.MedicationSupplyItem> get medicationItemsOrderedByRatio =>
      (super.noSuchMethod(
        Invocation.getter(#medicationItemsOrderedByRatio),
        returnValue: <_i6.MedicationSupplyItem>[],
      ) as List<_i6.MedicationSupplyItem>);

  @override
  List<_i3.SupplyItem> get allItemsOrderedByName => (super.noSuchMethod(
        Invocation.getter(#allItemsOrderedByName),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  List<_i3.SupplyItem> get medicationItemsOrderedByName => (super.noSuchMethod(
        Invocation.getter(#medicationItemsOrderedByName),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  List<_i3.SupplyItem> get genericItemsOrderedByName => (super.noSuchMethod(
        Invocation.getter(#genericItemsOrderedByName),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.SupplyItem> getItemsByIds(List<int>? ids) => (super.noSuchMethod(
        Invocation.method(
          #getItemsByIds,
          [ids],
        ),
        returnValue: <_i3.SupplyItem>[],
      ) as List<_i3.SupplyItem>);

  @override
  _i8.Future<void> fetchItems() => (super.noSuchMethod(
        Invocation.method(
          #fetchItems,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i6.MedicationSupplyItem? getMostUsedItemForMedication(
    _i9.Molecule? molecule,
    _i10.AdministrationRoute? administrationRoute,
    _i11.Ester? ester,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMostUsedItemForMedication,
        [
          molecule,
          administrationRoute,
          ester,
        ],
      )) as _i6.MedicationSupplyItem?);

  @override
  List<_i6.MedicationSupplyItem> getItemsForMedication(
    _i9.Molecule? molecule,
    _i10.AdministrationRoute? administrationRoute,
    _i11.Ester? ester,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsForMedication,
          [
            molecule,
            administrationRoute,
            ester,
          ],
        ),
        returnValue: <_i6.MedicationSupplyItem>[],
      ) as List<_i6.MedicationSupplyItem>);

  @override
  _i8.Future<void> deleteItem(_i3.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [item],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.SupplyItem> add(_i3.SupplyItem? supplyItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [supplyItem],
        ),
        returnValue: _i8.Future<_i3.SupplyItem>.value(_FakeSupplyItem_1(
          this,
          Invocation.method(
            #add,
            [supplyItem],
          ),
        )),
      ) as _i8.Future<_i3.SupplyItem>);

  @override
  _i8.Future<void> updateItem(_i3.SupplyItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i12.MedicationIntakeProvider {
  MockMedicationIntakeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i13.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i13.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i13.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<_i13.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  List<_i13.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  List<_i13.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  List<_i13.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  List<_i13.MedicationIntake> get plottableIntakes => (super.noSuchMethod(
        Invocation.getter(#plottableIntakes),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i13.MedicationIntake> getTakenIntakesDescForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesDescForSchedule,
          [scheduleId],
        ),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  _i8.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteIntake(_i13.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> add(_i13.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateIntake(_i13.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i14.GraphIntake> getIntakesForGraph(DateTime? tMin) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntakesForGraph,
          [tMin],
        ),
        returnValue: <_i14.GraphIntake>[],
      ) as List<_i14.GraphIntake>);

  @override
  _i15.Date? getLastIntakeLocalDateFromList(
          List<_i13.MedicationIntake>? intakes) =>
      (super.noSuchMethod(Invocation.method(
        #getLastIntakeLocalDateFromList,
        [intakes],
      )) as _i15.Date?);

  @override
  _i15.Date? getLastIntakeLocalDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(Invocation.method(
        #getLastIntakeLocalDateForSchedule,
        [scheduleId],
      )) as _i15.Date?);

  @override
  List<_i13.MedicationIntake> getTakenIntakesForScheduleOn(
    int? scheduleId,
    _i15.Date? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForScheduleOn,
          [
            scheduleId,
            date,
          ],
        ),
        returnValue: <_i13.MedicationIntake>[],
      ) as List<_i13.MedicationIntake>);

  @override
  _i13.MedicationIntake? getLastTakenIntakeForSchedule(int? scheduleId) =>
      (super.noSuchMethod(Invocation.method(
        #getLastTakenIntakeForSchedule,
        [scheduleId],
      )) as _i13.MedicationIntake?);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i16.MedicationScheduleProvider {
  MockMedicationScheduleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository<_i17.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i17.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i17.MedicationSchedule>);

  @override
  List<_i17.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i17.MedicationSchedule>[],
      ) as List<_i17.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i17.MedicationSchedule? getScheduleById(int? id) =>
      (super.noSuchMethod(Invocation.method(
        #getScheduleById,
        [id],
      )) as _i17.MedicationSchedule?);

  @override
  _i8.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteSchedule(_i17.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> add(_i17.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [schedule],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateSchedule(_i17.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupplyItemManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplyItemManager extends _i1.Mock implements _i18.SupplyItemManager {
  MockSupplyItemManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> useDose(
    _i6.MedicationSupplyItem? item,
    _i19.Decimal? doseToUse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #useDose,
          [
            item,
            doseToUse,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> use(
    _i7.GenericSupply? item, {
    int? quantity = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #use,
          [item],
          {#quantity: quantity},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> putBack(
    _i7.GenericSupply? item, {
    int? quantity = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putBack,
          [item],
          {#quantity: quantity},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> switchDoses(
    _i6.MedicationSupplyItem? previousItem,
    _i6.MedicationSupplyItem? nextItem,
    _i19.Decimal? previousDose,
    _i19.Decimal? nextDose,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchDoses,
          [
            previousItem,
            nextItem,
            previousDose,
            nextDose,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [LocaleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocaleProvider extends _i1.Mock implements _i20.LocaleProvider {
  MockLocaleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Locale get locale => (super.noSuchMethod(
        Invocation.getter(#locale),
        returnValue: _FakeLocale_2(
          this,
          Invocation.getter(#locale),
        ),
      ) as _i4.Locale);

  @override
  List<_i4.Locale> get supportedLocales => (super.noSuchMethod(
        Invocation.getter(#supportedLocales),
        returnValue: <_i4.Locale>[],
      ) as List<_i4.Locale>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setLocale(_i4.Locale? newLocale) => super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [newLocale],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> setFollowSystemLocale() => (super.noSuchMethod(
        Invocation.method(
          #setFollowSystemLocale,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
